global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'my-service'
    static_configs:
      - targets: ['134.34.126.52:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['134.34.126.52:9100']  # Assuming Node Exporter is running on the same host
